### ISSUE TITLE
Store Trillian Tree object in the Directory table

### ISSUE THREAD

**Issue by gdbelvin** [google/keytransparency#1152]
Each operation currently touches the Trillian Admin API in order to retrieve the public keys and other static configuration information for the the Trillian Tree. This is both less secure, and induces many unnecessary RPCs.

By storing relevant parts of the the Trillian.Tree object in the directory table we can remove these RPCs and possibly also remove quite a few references to the Trillian admin API from the code.

**Comment by Zyqsempai** [comment]
Sounds like a fun) I can take this one.

**Comment by Zyqsempai** [comment]
It would be great if you could list the parts of Tree you want to move to Directory table.

**Comment by gdbelvin** [comment]
I've just created #1165 which trims the Tree info down to the essential pieces that Key Transparency needs for verification. 

It might be tempting to split out all fields separately for storage in the database, but it may be easier and more future proof to just store the serialized proto of the `trillian.Tree`

**Comment by Zyqsempai** [comment]
Sounds quite reasonable, also it will make `pb.Directory{}` more consistent with `directory.Directory{}` struct.

**Comment by gdbelvin** [comment]
Indeed it would. That would be very nice.
