### ISSUE TITLE
docker-compose expects unset ${TRAVIS_COMMIT} from environment 

### ISSUE THREAD

**Issue by DazWilkin** [google/keytransparency#1156]
The docker-compose file takes a dependency on environment variable `TRAVIS_COMMIT`.

There is no default for this value (perhaps `latest`?) and the [`README`](https://github.com/google/keytransparency/blob/master/README.md) does not explain what value it should take though these appear to match the git commits.

Looking at the following, using `default` works but is likely not recommended:

`gcloud container images list-tags us.gcr.io/key-transparency/log-server`

**Comment by gdbelvin** [comment]
The default value should be `latest`.  I think we could add that to the script with some bash magic.

**Comment by DazWilkin** [comment]
You are correct. I should not have suggested using `latest`. IIRC Trillian has a way to do something similar. Images get tagged by commit SHA and then the bash scripts compute the latest value for the Kubernetes deployments. It's not something I've done myself.

**Comment by DazWilkin** [comment]
See `${IMAGE_TAG)` here:
https://github.com/google/trillian/blob/master/examples/deployment/kubernetes/deploy.sh

[Sorry, phone challenged]

**Comment by gdbelvin** [comment]
I have a very similar script here:
https://github.com/google/keytransparency/blob/master/scripts/deploy.sh 

I could add that bit of logic to handle the case where `TRAVIS_COMMIT` is not set, but this wouldn't handle the case where users just cd to the home directory and run `docker-compose up`

**Comment by DazWilkin** [comment]
I think there are 3 options:

- manually tag images versions you deem good and then revise the `docker-conpose`

- regenerate the `docker-company` with the latest tags as part of your CI/CD

- parameterize `docker-compose` from the environment and make it depend on the bash that sets the value.

I think there no pre-processor for compose.
