### ISSUE TITLE
[keytransparency-client] Add flag specify .keyset location

### ISSUE THREAD

**Issue by DazWilkin** [google/keytransparency#1213]
`keytransparency-client` appears to not permit specifying the location of `.keyset`.

This makes debugging more challenging because:
- the working directory (where `.keyset` is created) becomes more of a moveable feast.
- debugging `keytransparency-client` commands e.g. `post` depend on `.keyset` existing

**Recommend**: 
Add a flag to support specifying the location (and name?) of `.keyset`

**Comment by Zyqsempai** [comment]
I can take this one.
