### ISSUE TITLE
Define revisions asynchronously

### ISSUE THREAD

**Issue by pavelkalinnikov** [google/keytransparency#1333]
Currently KT server runs [`RunBatch`](https://github.com/google/keytransparency/blob/aac75b12117ce93a11ed04b2f55133866651450f/core/sequencer/server.go#L231) method which does two things sequentially:

1. Define what goes into the next revision (in `DefineRevision` method).
2. Build the new revisions of the map in accordance with these definitions (in `ApplyRevision` method).

The issues with this approach:

1. Defining future batches blocks working through the backlog. These steps can be done in parallel.
2. If `ApplyRevision` is much slower than the incoming mutations flow then `DefineRevision` will keep returning longer and longer slices of revisions, and `RunBatch` call will increasingly become heavier. As a side effect of that, the corresponding `RunBatch` RPC trace will grow uncontrollably, etc.

**Comment by pavelkalinnikov** [comment]
The proposed solution:

- Factor out the loop of defining revisions into a separate background task.
- Make it so that the `RunBatch` only reads the already defined batches from the database.
- Limit max number of revisions that `RunBatch` can go through. Possibly even make it so that it only builds one at a time.
- Possible optimization: channel the defined revisions from the batch defining task to the revision building task, to avoid the redundant database reads. This will match nicely with the one-batch-at-a-time idea.

**Comment by gdbelvin** [comment]
>  if ApplyRevision is much slower than the incoming mutations flow then DefineRevision will keep returning longer and longer slices of revisions,. As a side effect of that, the corresponding RunBatch RPC trace will grow uncontrollably, etc.

[`MaxBatchSize`](https://github.com/google/keytransparency/blob/master/core/sequencer/sequencer.go#L132) should prevent the batch size from growing uncontrollably.
