### ISSUE TITLE
missing google/tink/go/insecure

### ISSUE THREAD

**Issue by n2vi** [google/keytransparency#1390]
When I blindly follow Setup step 2 in google/keytransparency/README.md, I get a missing package:

$ go get github.com/google/keytransparency/cmd/keytransparency-client
go: finding golang.org/x/oauth2 latest
go: finding google.golang.org/genproto latest
go: finding golang.org/x/crypto latest
go: finding github.com/golang/glog latest
go: finding golang.org/x/time latest
go: finding golang.org/x/net latest
build github.com/google/keytransparency/cmd/keytransparency-client: cannot load github.com/google/tink/go/insecure: module github.com/google/tink@latest found (v1.2.2), but does not contain package github.com/google/tink/go/insecure

My workaround is:
git clone https://github.com/google/keytransparency
cd keytransparency/cmd/keytransparency-client
go install

**Comment by gdbelvin** [comment]
Hypothesis: when `go get` looks for the latest version of KT, it finds an old, broken release.
Solution: #1385

**Comment by gdbelvin** [comment]
Fixed by tagging `v0.1.3`
