### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [google/keytransparency#1612]
The README file in this repo has a bad link - [404:NotFound]

Status code [404:NotFound] - Link: https://github.com/google/keytransparency/blob/master/impl/sql

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by pphaneuf** [comment]
Fixed it in c1d8b03b87f098b18637b89ab17ff4c1c49fd1e2, thanks!
