### ISSUE TITLE
[client] get key format cleanup

### ISSUE THREAD

**Issue by cesarghali** [google/keytransparency#331]
Running the following set of commands:
1. `goreman start`
2. `./key-transparency-client post <email> -d '{"app1": "dGVzdA=="}' --config=./.key-transparency.yaml --verbose`
3. `./key-transparency-client get <email> --config=.key-transparency.yaml`

returns:

```
Profile for <email>: keys:<key:"app1" value:"test" >
```

Desired output:

```
{"app1": "dGVzdA=="}
```

**Comment by gdbelvin** [comment]
Fixed
