### ISSUE TITLE
Save Commitment after CheckMutation

### ISSUE THREAD

**Issue by cesarghali** [google/keytransparency#425]
In [UpdateEntry](https://github.com/google/key-transparency/blob/master/core/keyserver/keyserver.go#L205), we're currently saving the commitment after we verify the request validity but before we verify the mutation. We might want to save it after both verification operations pass.

@gdbelvin what do you think?

**Comment by gdbelvin** [comment]
Sounds good

**Comment by gdbelvin** [comment]
Now that Key Transparency is storing commitments as mapleaf.ExtraData, this is no longer an issue.
