### ISSUE TITLE
Migrate to `pkg/context`

### ISSUE THREAD

**Issue by cesarghali** [google/keytransparency#431]
These two packages look the same. Any specific reason why we are using `golang.org/x/net/context` and not `context`?

**Comment by cesarghali** [comment]
We cannot use `context` instead of `golang.org/x/net/context` without breaking gRPC APIs. I will close this issue.

**Comment by gdbelvin** [comment]
Relevant tracking bug: https://github.com/grpc/grpc-go/issues/711
