### ISSUE TITLE
Client Should Be Anonymous When Calling GetEntry API 

### ISSUE THREAD

**Issue by cesarghali** [google/keytransparency#506]
Currently, the client can be configured to either use a service key or a client secret (which is translated into an OAuth token). If both are configured, client secret takes over which doesn't make `GetEntry` anonymous. For `GetEntry` to be anonymous, client config should be changed every time `GetEntry` is called after `UpdateEntry` and vice versa.

There should be a flexible way to specify authentication requirements for each API.

**Comment by gdbelvin** [comment]
After some chats, I'm reconsidering this requirement. 

Motivating use cases: 
- Users that want to block someone from talking to them, or discovering when they change keys. 
- Blocking accounts that are engaging in spammy behavior. 
- Blocking accounts that are engaging in DoS behavior. 

Motivating use cases for an anonymous get function:
- Obtain key material without revealing identity of communicating parties.
- Obtain key material without needing to rely on gossip for consistency. 

The current setup of an OAuth and service keys is adding extra complexity to the client without obvious benefit and make it more difficult to use.  Until we have a properly anonymous Get function, consider reverting to OAuth for all operations. 

As a future feature, anonymous tokenization schemes might be able to meet both requirements.

**Comment by n2vi** [comment]
Upspin solved the problem by removing authentication token generation in
the client and token checking in the server for key fetch, but of course
still requiring auth for all other operations.  Some of our users say lack
of anonymous GetEntry would be a showstopper.

Consider that your users could create a series of accounts like
anonymous1234@example.com and publish the keys.  So real identification or
blocking is impossible anyway, though you can add complexity to the client
if you attempt that arms race.

In Upspin, blocking by user is in effect done at the client.  All keys and
key changes are public.  The key server is intended to be fast enough to
absorb DoS.   There is no reason you should do it our way, just pointing
out the existence proof.

**Comment by gdbelvin** [comment]
Fixed by #975
