### ISSUE TITLE
Batch APIs

### ISSUE THREAD

**Issue by gdbelvin** [google/keytransparency#588]
APIs:
- [x] Batch GetUser
  Supports looking up {self, others} in one go. 
- [x] Batch UpdateEntry
   Assumes that user authentication has occurred upstream. Authentication and authorization may be implemented as grpc interceptors.

**Comment by gdbelvin** [comment]
New use-case: a single user updating multiple trees with a single API end point.

**Comment by jtoohill** [comment]
Is a batch API needed for that? IIUC there's no transactionality or log consistency required across trees.

What I would like a batch API for is looking up multiple leaves in a given tree in a single request, which should return entries all in the same epoch (and only requiring a single consistency proof).

**Comment by gdbelvin** [comment]
You're right. That's not an actual use case. I'll add a batch API for lookups to the top.
