### ISSUE TITLE
Allow file based configuration

### ISSUE THREAD

**Issue by Liamsi** [google/keytransparency#597]
Similar to https://github.com/google/trillian/pull/620 
~~And (if not resolved by #578): `frontend.go` should read the actual PEM file (see https://github.com/google/keytransparency/pull/578#discussion_r120088973)~~

@gdbelvin proposed using https://github.com/namsral/flag

**Comment by gdbelvin** [comment]
At the moment, we're not seeing a strong demand for this.  We can reopen at a later point if interest comes around.
