### ISSUE TITLE
Continuous Integration Server

### ISSUE THREAD

**Issue by gdbelvin** [google/keytransparency#601]
It would be awesome to have a server that tracked HEAD

A few options:
https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes

Docker hub seems to be down:
https://github.com/docker/hub-feedback/issues/590
https://docs.docker.com/docker-hub/github/#github-organizations

**Comment by Liamsi** [comment]
This seems related: https://github.com/google/trillian/issues/495
