### ISSUE TITLE
.keytransparency.yaml out of date

### ISSUE THREAD

**Issue by AMarcedone** [google/keytransparency#604]
It references 
`log-key: "../trillian/testdata/ct-http-server.pubkey.pem"`
while I think it should be:
`log-key: "../trillian/testdata/log-rpc-server.pubkey.pem"`

**Comment by cesarghali** [comment]
Thanks for reporting this Antonio. If this fixes an issue you're having with the client, then we need to fix it. Feel free to create a PR and add me as a reviewer.

**Comment by AMarcedone** [comment]
Well, I get a file not found error. The client still has other issues and
is not fully working for me, but this is a step in the right direction.
Will do!

**Comment by Liamsi** [comment]
> while I think it should be:
> log-key: "../trillian/testdata/log-rpc-server.pubkey.pem"

That's correct. For the server side this is already fixed in the current [docker-compose.yml](https://github.com/google/keytransparency/blob/master/docker-compose.yml) file.
Also, `mapid` needs to be `map-id` in the .keytransparency.yaml file.

**Comment by AMarcedone** [comment]
I'll add that change too. Thanks :)

**Comment by AMarcedone** [comment]
A related modification would be to have a more informative error message
(rather than the generic "no rows in sql result") whenever one tries to
access a tree which does not exists. That would have saved me a bit of time.

**Comment by Liamsi** [comment]
This is an [error](https://golang.org/pkg/database/sql/#pkg-variables) coming directly from the sql request "forwarded" by the (trillian) interceptor/[error wrapper](https://github.com/google/trillian/blob/4c32305990c7199db8ce56d3143295abb5fbc0c7/server/errors/errors.go#L30). The interceptor could prefix it with a more human-friendly message but I guess this isnn't sth. which will be shown to any (end-)user anyways. Not sure how I feel about this.

**Comment by Liamsi** [comment]
Thinking about it further: I think you are right. The command-line client could parse the error code (`codes.NotFound`) and give a more informative message. It might make sense to sync up with  @gdbelvin before you do any changes in the client (and not only in the yml file) though. He might already have a better idea/other plans.

**Comment by AMarcedone** [comment]
Cool, let's wait for him :)

**Comment by Liamsi** [comment]
No need to wait. If you already found a simple solution feel free submit it in a separate pull request.

**Comment by AMarcedone** [comment]
I am investigating a solution. 
A possibly confusing behavior is that the client has a map-id flag, but such flag is just (at least) used for verifying some proofs and is not sent as part of the GetEntry request to the server (which I would expect).
Is this the expected?

**Comment by Liamsi** [comment]
Not hundert percent sure this is intended but if the kt server is supposed to only hold one map-id (which seems to be the case on first sight) it's OK that the client doesn't send it with the request. The client would still need to know the map-id for verifying responses. The server needs a map-id to request the correct trillian signed map root.

**Comment by AMarcedone** [comment]
See https://github.com/AMarcedone/trillian/commit/914d5dc02e3d9c3cdd55ba2f824b489ccdc6a356

(I will make a pull request once the CLA issues get sorted out)

**Comment by AMarcedone** [comment]
https://github.com/AMarcedone/keytransparency/commit/150a32c2f28cd681a45970c7a73d333d235fdf26
(will make the pull request once the CLA stuff is sorted out)

**Comment by gdbelvin** [comment]
Thanks for pointing this out @AMarcedone. This caused me to burn a bunch of time too. 
The appropriate thing to do would be to add a `fmt.Errorf("Tree not found: %v, err)` message inside the appropriate block in the Trillian map [interceptor](https://github.com/google/trillian/blob/4c32305990c7199db8ce56d3143295abb5fbc0c7/server/interceptor/interceptor.go#L39). 

@codingllama, what do you think?

**Comment by codingllama** [comment]
I haven't followed the entire discussion, but from what I gather sounds good.

What's the error message you're currently getting?

**Comment by gdbelvin** [comment]
I believe the current message is
"sql: no rows in result set"

I think it's coming from inside the interceptor when it tries to retrieve
the appropriate tree config.
Since all the error blocks simply "return err", this is what bubbles up to
the user.

**Comment by Liamsi** [comment]
Exactly, it comes from [here](https://github.com/google/trillian/blob/4c32305990c7199db8ce56d3143295abb5fbc0c7/server/errors/errors.go#L30) in combination with this [error](https://golang.org/pkg/database/sql/#pkg-variables).

**Comment by codingllama** [comment]
Oh right, that's not very helpful. :)

The NotFound in conjunction with the RPC called is the defining factor, but the hops between KT and Trillian likely make things muddled even further for KT users.

I'm not entirely sure on which RPC is being called in this case, but I'm guessing that adding some context at [interceptor.go](https://github.com/google/trillian/blob/4c32305990c7199db8ce56d3143295abb5fbc0c7/server/interceptor/interceptor.go#L51), like `fmt.Errorf("tree %v not found: %v", treeID, err)`, would fix this for you. Give me a nudge if you agree and I'll put a PR together.

**Comment by gdbelvin** [comment]
That would be perfect.  A simple PR to that effect would be awesome.

**Comment by codingllama** [comment]
FYI: https://github.com/google/trillian/pull/682.

**Comment by AMarcedone** [comment]
LGTM. Thanks!
