### ISSUE TITLE
Performance numbers

### ISSUE THREAD

**Issue by Liamsi** [google/keytransparency#645]
Copied from #587:

> Desired graphs:
> - Load (mutations/sec or epoch) vs. signing time
>
> Add Prometheus counters:
> - Total mutations processed
> - Total indexes processed
> - Total signing time
> - Total map update time
>
> Existing:
> - Get latency
> - Update latency

**Comment by gdbelvin** [comment]
The last load test go us 60QPS, with the bottle neck being the number of concurrent SQL transactions to a single homed mysql backend for Trillian.
