### ISSUE TITLE
kt-signer does not sign

### ISSUE THREAD

**Issue by Liamsi** [google/keytransparency#651]
On a fresh start of the kt-signer:

`CreateEpoch failed: sths.Write(8149281774419562536, 1): signature is nil`

after restarting the signer:

`CreateEpoch failed: sths.Write(8149281774419562536, 2): rpc error: code = DeadlineExceeded desc = context deadline exceeded` 

Might be related to trillian's `sequencer_interval`?
If lowering the sequencing interval is the appropriate way to resolve this we could document this somewhere.
To reproduce, see logs in kubernetes deployment:
```
ktsigner=`kubectl get pods --selector=run=kt-signer -o jsonpath={.items[*].metadata.name}`
kubectl logs $ktsigner
```

**Comment by gdbelvin** [comment]
Sounds like this is an issue with the trillian log failing to sign.  Please create an issue in the trillian repo and link to it.

**Comment by Liamsi** [comment]
**Update**: Signing times out here https://github.com/google/trillian/blob/2227dd6524ecbf46dadf42788bd27215ed061cba/client/client.go#L180-L185

google/trillian#692 might resolve this
