### ISSUE TITLE
failed to read: ../trillian/testdata/ct-http-server.pubkey.pem. 

### ISSUE THREAD

**Issue by juniway** [google/keytransparency#658]
"error connecting: Failed to open public key <nil>: failed to read: ../trillian/testdata/ct-http-server.pubkey.pem. open ../trillian/testdata/ct-http-server.pubkey.pem: no such file or directory"

the above error happens when I execute the following command as suggested in the Using the Key Transparency Client seciton.
./keytransparency-client post user@domain.com app1 -d 'dGVzdA==' --config=./.keytransparency.yaml

also, from the instruction "3. Get an OAuth client ID and download the generated JSON file."  I can't get how and where to use this generated JSON file, a more detailed instruction will be helpful?

**Comment by Liamsi** [comment]
Thanks for trying out key-transparency! The error you are stumbling upon indicates that your working directory might be out of date or you did run `scripts/prepare_client.sh` and it overwrote the file with the wrong values. 

To get the client running you can manually edit `.keytransparency.yaml`. Change the following lines to:
`log-key: "../trillian/testdata/log-rpc-server.pubkey.pem"`
`client-secret: "client_secret.json"`

>also, from the instruction "3. Get an OAuth client ID and download the generated JSON file." I can't get how and where to use this generated JSON file, a more detailed instruction will be helpful?

The `client-secret` line from above should point to this file (relative or absolute paths should work). The client will use it to authenticate you against Google's OAuth2 API.

The `.keytransparency.yaml` client config was updated with this commit: https://github.com/google/keytransparency/commit/fe386b3560b93908479ae5d9b2e7088620df0bf0#diff-9cc5b431d33ba7ed4d634c8e51f4e7df but we didn't update the scripts for the client yet.

The defaults in `prepare_client.sh` seem out of date. I opened an issue to track this: #659

**Comment by juniway** [comment]
ok, things looks correct right now, do I have to set up a server (./script/prepare_server.sh) so that I can do the test, or is there a testing network I can use?  when I execute `prepare_server.sh`, I get this error:
```
Database engine: SQLite or MySQL?
1) SQLite
2) MySQL
#? 2
MySQL DSN (more info https://github.com/go-sql-driver/mysql): mysql:host=localhost;dbname=test
Path to application credentials file: ~/.ssh/id_rsa.pub
Listen IP address, e.g., localhost, (to listen on all IPs, use empty string): localhost
Frontend domain name (optional):
Frontend public IP address (optional):
Generating RSA private key, 2048 bit long modulus
........................................................................................................................
.............................+++
..........................................................................................................+++
e is 65537 (0x010001)
140665032314752:error:28069065:UI routines:UI_set_result:result too small:crypto/ui/ui_lib.c:778:You must type in 4 to 1023 characters
140665032314752:error:28069065:UI routines:UI_set_result:result too small:crypto/ui/ui_lib.c:778:You must type in 4 to 1023 characters
140665032314752:error:0906906F:PEM routines:PEM_ASN1_write_bio:read key:crypto/pem/pem_lib.c:336:
unable to load Private Key
139854427090816:error:0906D06C:PEM routines:PEM_read_bio:no start line:crypto/pem/pem_lib.c:691:Expecting: ANY PRIVATE KEY
chmod: cannot access 'server.key': No such file or directory
Can't open server.key for reading, No such file or directory
139882963976064:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:74:fopen('server.key','r')
139882963976064:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:81:
unable to load Private Key
```
any hints where I was wrong?  what specifically are `application credentials file`? thanks for help

**Comment by Liamsi** [comment]
I would recommend running a server yourself!
Just run the script with the `-f` flag. It will pick defaults for a test-environment: `scripts/prepare_server.sh -f`

**Comment by Liamsi** [comment]
All the mentioned problems are currently tackled in #660 #656

**Comment by gdbelvin** [comment]
The Readme has been updated. There are probably a few minor errors left that we'll iron out tomorrow, but on the whole it should be much more sane. Let us know if you have any issues!

**Comment by juniway** [comment]
Actually I get the same errors on executing `scripts/prepare_server.sh -f`, so I looked into the `scripts/gen_server_keys.sh`, found out the error messages "UI routines:UI_set_result:result too small:crypto/ui/ui_lib.c:778:You must type in 4 to 1023 characters" come from this command(line 42 & 43):
```shell
openssl genrsa -des3 -passout pass:x -out server.pass.key 2048
openssl rsa -passin pass:x -in server.pass.key -out server.key
```
basically it says I need to provide a default password with at least 4 characters, so I change `pass:x` to `pass:xxxx` and now it works.

**Comment by gdbelvin** [comment]
What machine is this on?  This seems to work fine for me on both Mac and Linux. 
Would be happy to accept a PR to fix it

**Comment by Liamsi** [comment]
@juniway can you also give us the output of `openssl version` on ypour machine?

**Comment by juniway** [comment]
Sorry for the late response, I test this on Arch Linux with openssl 1.1.0. When I test it on another machine with openssl 1.0.2g,  `pass:x` works fine, so it turns to be a compatible issue with openssl 1.1.0
