### ISSUE TITLE
Server should publish verification data 

### ISSUE THREAD

**Issue by gdbelvin** [google/keytransparency#672]
There should be an API for requesting the data needed to verify a particular KT server. 
This data should never change for a particular stable instance of KT and clients should have this information, or a hash of this information baked in, but it is a useful convenience feature and supports discovery of new KT servers.

**Comment by gdbelvin** [comment]
Let's publish this info at 
`v1/domain/info`

When we have multiple domains per server this can be 
`v1/domains/{}/info`

**Comment by Liamsi** [comment]
Will return json containing:
```
{
mapTree: [...],
logTree: [...]
}
```
This basically relays requests to trillian's admin API: [trillian_admin_api.proto](https://github.com/google/trillian/blob/master/trillian_admin_api.proto#L81-L85). 
Responses of this API should be cached to keep unnecessary load from the log/map server.

**Comment by gdbelvin** [comment]
Looks great

**Comment by Liamsi** [comment]
Thanks! Updated my comment above to include the VRF key.

**Comment by Liamsi** [comment]
![screenshot from 2017-08-01 16 40 44](https://user-images.githubusercontent.com/7441766/28834711-f576572a-76da-11e7-8e13-5077b74248b7.png)
