### ISSUE TITLE
Expose Querying GetMutations HTTP API

### ISSUE THREAD

**Issue by Liamsi** [google/keytransparency#685]
Querying `/v1/epochs/1` returns "Not Found" although epoch 0 and 1 have passed (and were signed)

Seems like the existing `MutationService` is not registered yet. 
- [ ] register service

**Comment by Liamsi** [comment]
Seems like the existing `MutationService` is not registered yet.

**Comment by cesarghali** [comment]
Right. When this service was implemented, we didn't have working binaries, so I didn't register it since there was no way to test that.

**Comment by Liamsi** [comment]
Thanks for the explanation @cesarghali. I changed the title title to better reflect what is going on.
