### ISSUE TITLE
libtool is required as a dependency to build the client

### ISSUE THREAD

**Issue by AMarcedone** [google/keytransparency#687]
```
~/go/src/github.com/google/keytransparency(master*) » go get -u github.com/google/keytransparency/cmd/keytransparency-client                                                                                                                   
# github.com/miekg/pkcs11
../../miekg/pkcs11/pkcs11.go:29:10: fatal error: "ltdl.h" file not found
#include <ltdl.h>
         ^
1 error generated.
------------------------------------------------------------
```

`brew install libtool` solves the issue on mac. I suggest documenting this in the readme.

**Comment by Liamsi** [comment]
Thanks @AMarcedone! This is due to: https://github.com/google/trillian/pull/611 

Maybe we should have a Dockerfile spinning up the client to recognise such issues automatically (on travis).

**Comment by gdbelvin** [comment]
@RJPercival <https://github.com/RJPercival> is working on removing this
dependency from the default trillian build.

**Comment by AMarcedone** [comment]
@RJPercival and @gdbelvin: what is the status/eta with this? 
I am working on a kt java client ( #711 ). It seems that gobind does not play well with cgo (at least I am having trouble integrating the libtool library), so removing the dependency on pkcs11 would be helpful for me. Otherwise I can try to work around this and get the library to work or remove the dependency myself on a separate branch.

**Comment by RJPercival** [comment]
PR google/trillian#734 fixes this, but is still under review. Shouldn't be long before it merges though.

**Comment by AMarcedone** [comment]
That's great! I'll just checkout that branch for now. Thanks!

**Comment by gdbelvin** [comment]
The Trillian fixes are in! I'll be updating the docker files to be faster shortly, but you should be unblocked with respect to Trillian
