### ISSUE TITLE
Deployed kt server's ssl cert has the wrong ip

### ISSUE THREAD

**Issue by AMarcedone** [google/keytransparency#724]
The ssl server deployed from travis has a (self signed) cert for 0.0.0.0 and not its actual ip (currently 35.184.134.53), therefore the connection from the client fails (using a browser allows to ignore the issue).

In addition, it would be great to expose the ssl cert as a file so it is easy to download and pass to the client as an argument (but I am now looking for some openssl commands to automatically download it)

**Comment by Liamsi** [comment]
I actually had a slightly differnt problem while working on the monitor. The error I've seen complained about the SAN domain being different: https://github.com/google/keytransparency/pull/709/files#diff-5c850f75b7eacb9380d3418499444d87R36

I'll run the deploy script with patched scripts and let's see if this already solves the problem. Otherwise, I'll fix the script (unfortunately not today).

**Comment by Liamsi** [comment]
I updated the scripts and deployed from my machine to gke with SAN:
DNS Name: kt-server
IP Address: 35.184.134.53

Will update the scripts soon! Maybe as part of the monitor PR, or in a separate pull if this blocks you.

If this still doesn't work you can work with `grpc.Dial(urlOrIP, grpc.WithInsecure())` to not be blocked (add a big warning comment to not forget to change that). Alternatively, there might be a way to tell grpc to trust this particular cert.

**Comment by AMarcedone** [comment]
Using the WithInsecure option does not work (I think the server only accepts secure connections, as I get  `Error: GetEntry failed: rpc error: code = Unavailable desc = transport is closing`)

However I was able to solve the problem by saving the DER encoded .cer certificate through chrome, converting it with `openssl x509 -inform DER -in US.cer -out servercert.crt` and passing it to the client using the `kt-key` flag in .key-transparency.yaml.

Btw, I think we should clarify names for all these keys, certificates and flags. Even after working on the project for a while, they are still confusing.

**Comment by Liamsi** [comment]
> Btw, I think we should clarify names for all these keys, certificates and flags. Even after working on the project for a while, they are still confusing.

+1

**Comment by gdbelvin** [comment]
Agreed on clarifying the flag names.  I've got a PR queued up for this.
