### ISSUE TITLE
Change hash function back pointer to be SHA256

### ISSUE THREAD

**Issue by gdbelvin** [google/keytransparency#745]
Since the map stores leaf objects as `[]byte` it doesn't make sense to use ObjectHash. We can just use a regular hash function.

**Comment by Liamsi** [comment]
Thanks for chiming in @benlaurie :-) 

Currently, the trillian map represents/stores leaf data in [`[]byte`](https://github.com/google/trillian/blob/e11b1d5427f8e8505bf8713b8e434f125449d74e/trillian_map_api.proto#L31) (independent from what you store there). My understanding is a back pointer to a leaf should be a hash of these raw bytes in the leaf (for which we could use sha256). 
Are you suggesting we should change from bytes to some other non-marshaled, general representation of the data on the trillian side (and hash this for a back pointer)?

**Comment by gdbelvin** [comment]
Thanks for your input @benlaurie!  

To my thinking this seems to be a question of semantics?  The Trillian map stores leaf data as `[]byte` as @Liamsi mentioned.  We have a couple choices for making a hash chain for each leaf revision:
1. Hash of the previous revision's `[]byte` representation.  
   - Easy to understand, hard to mess up.
   - Forces the hash to change if there's a change in representation. eg. redacting a field, re-ordering proto elements, etc. 
2. Hash of the previous revision's ObjectHash. 
   - Forces object serialization to JSON or at least a decode/encode step through JSON
       - Introduces the possibility of accidentally dropping unknown fields. 
   - Hash wouldn't change on field reordering, redaction etc. 

To my intuition, the option of using the raw bytes seems stricter and safer.

**Comment by gdbelvin** [comment]
Fixed some timeago
