### ISSUE TITLE
Update documentation so that make presubmit works

### ISSUE THREAD

**Issue by cesarghali** [google/keytransparency#805]
If this is not already done, we should mention somewhere in the documentation what commands should be installed before running `make presubmit`.

**Comment by gdbelvin** [comment]
The only item that are needed for `make presubmit` to work now are the same commands in `.travis`: 
```
go get -u github.com/alecthomas/gometalinter
gometalinter --install
```

I thought about adding these two lines to the `Makefile` but I'm not sure it's worth it. 
What do you think?

**Comment by gdbelvin** [comment]
The make file has been replaced with:
```
go build ./...
go test ./...
gometalinter ./...
```
