### ISSUE TITLE
Implement domain garbage collection

### ISSUE THREAD

**Issue by gdbelvin** [google/keytransparency#848]
Domains that have been deleted for more than X days should be removed from the database.

**Comment by Zyqsempai** [comment]
Is this one still actual? Maybe for directories marked as deleted.

**Comment by Zyqsempai** [comment]
Already implemented;) Just found it.

**Comment by gdbelvin** [comment]
We have an API endpoint that implements garbage collection, but nothing to call the garbage collector periodically. At the moment, that's probably safer.  Fixing this is a simple as adding a periodic callback in main.go
