### ISSUE TITLE
Sequencer's endpoints won't start

### ISSUE THREAD

**Issue by Scratch-net** [google/keytransparency#868]
Hello everyone, 
I tried to run KT on my environment but could not create a domain. After some digging I found the following problem in Sequencer's main.go:

When calling 
```
signer.StartSequencingAll(ctx, *refresh)
```
it never returns because of the blocking **for** loop
so, 
```
run(adminServer)
```
is never called.

Calling **signer.StartSequencingAll** in a separate goroutine seems to fix the problem, however I'm not sure if this is the proper way to do it

**Comment by gdbelvin** [comment]
Thanks for pointing this out.  Your solution is indeed correct.  Please see #904
